@RegisterAPI_HostAddress = https://localhost:7101

### Test the default weather endpoint
GET {{RegisterAPI_HostAddress}}/weatherforecast/
Accept: application/json

### Test the registration endpoint
POST {{RegisterAPI_HostAddress}}/api/register
Content-Type: application/json

{
    "NIT": "123456789",
    "Email": "test@example.com",
    "PhoneNumber": "1234567890",
    "Password": "password123"
}
